-- main page 메뉴 용 테이블

create table mos_member
(
    member_seq    bigint generated by default as identity
        primary key,
    created_date  timestamp    not null,
    description   varchar(500) not null,
    email_address varchar(100) not null
        constraint uk_i2ysqcsp88l4i3ysoqk0wtsmv
            unique,
    first_name    varchar(45)  not null,
    image_path    varchar(100) not null,
    introduction  varchar(50)  not null,
    last_name     varchar(45)  not null,
    nick_name     varchar(40)  not null
        constraint uk_rmt7nfch3s16rr2llkyt4mks6
            unique,
    site_link     varchar(100) not null,
    use_yn        boolean      not null
);

create index mos_member_index_1
    on mos_member (nick_name);

create table skill
(
    skill_seq    bigint generated by default as identity
        primary key,
    created_date timestamp   not null,
    skill_name   varchar(15) not null
        constraint uk_1ledx6hfgc5c7ht0js8bmdqs0
            unique,
    skill_type   varchar(20) not null
        constraint uk_ab89p3834wnhurb7taaky0lp6,
    use_yn       boolean     not null
);

create index skill_index_1
    on skill (skill_name);

create table member_skill
(
    mos_members_member_seq bigint not null
        constraint fkgpt8o6k8ek2hxuq93etle86ms
            references mos_member,
    skills_skill_seq       bigint not null
        constraint fkk1eueu2gp3bt88uy5g85vkgpp
            references skill
);

INSERT INTO public.mos_member (member_seq, created_date, introduction, description, email_address, first_name,
                               image_path, last_name, nick_name, site_link, use_yn)
VALUES (1, '2022-10-11 21:37:08.128000', 'I''m Rubok, Backend Developer',
        'I''m Backend Developer. I work in Fassto. Fassto is Fullfillment Service provider Company.',
        'truespring1@gmail.com', 'seok', 'images/1', 'gyuhwan', 'rubok', 'https://github.com/truespring', true);

INSERT INTO public.skill (skill_seq, created_date, skill_name, skill_type, use_yn)
VALUES (1, '2022-10-11 21:36:54.705000', '백엔드', 'BACKEND', true);
INSERT INTO public.skill (skill_seq, created_date, skill_name, skill_type, use_yn)
VALUES (2, '2022-10-11 21:36:54.705000', '프론트엔드', 'FRONTEND', true);
INSERT INTO public.skill (skill_seq, created_date, skill_name, skill_type, use_yn)
VALUES (3, '2022-10-11 21:36:54.705000', '데브옵스', 'DEVOPS', true);
INSERT INTO public.skill (skill_seq, created_date, skill_name, skill_type, use_yn)
VALUES (4, '2022-10-11 21:36:54.705000', '데이터베이스', 'DATABASE', true);
INSERT INTO public.skill (skill_seq, created_date, skill_name, skill_type, use_yn)
VALUES (5, '2022-10-11 21:36:54.705000', '인프라', 'INFRA', true);
INSERT INTO public.skill (skill_seq, created_date, skill_name, skill_type, use_yn)
VALUES (6, '2022-10-11 21:36:54.705000', '서버', 'SERVER', true);
INSERT INTO public.skill (skill_seq, created_date, skill_name, skill_type, use_yn)
VALUES (7, '2022-10-11 21:36:54.705000', '인공지능', 'AI', true);
